security:
  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  encoders:
    App\Security\AuthUser:
      algorithm: bcrypt
      cost: 12

  providers:
    db_provider:
      id: App\Security\UserProvider

  role_hierarchy:
    ROLE_ADMIN: ROLE_ADMIN
    ROLE_USER: ROLE_USER

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    web:
      pattern: ^/
      user_checker: App\Security\UserChecker
      anonymous: ~
      remember_me:
        name: rmeawc
        secret:   '%kernel.secret%'
        lifetime: 604800 # 1 week in seconds
        path:     /
      provider: db_provider
      form_login:
        login_path: login
        check_path: login
        csrf_token_generator: security.csrf.token_manager
        require_previous_session: false
        default_target_path: index
        use_referer: true
      logout:
        path:   app_logout
        target: /

  access_control:
    - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin, roles: ROLE_ADMIN }