services:
  _defaults:
    autowire: false
    autoconfigure: true
    public: false

  # Global MailSender
  App\Mail\MailSender:
    arguments:
      - '@mailer'
      - '@twig'
      - '%app.name%'

  App\Mail\Builder\RentChangeStatusSender:
    arguments:
      - 'no-reply@adoramedia.com'
      - '@router'

  App\Mail\Sender\RentChangeStatusSender:
    arguments:
      - '@App\Mail\MailSender'
      - '@App\Mail\Builder\RentChangeNewBuilder'