services:
  _defaults:
    autowire: false
    autoconfigure: true
    public: true

  # CreateUserTest
  App\Tests\CreateUserTest:
    arguments:
      $createUserHandler: '@App\Service\Handler\CreateUserHandler'